### ISSUE TITLE
bad substitution

### ISSUE THREAD

**Issue by jterryfr** [SecureBankingAcceleratorToolkit/securebanking-openbanking-demo#10]
running `bin/config.sh init` as instructed in the docs returns an error

```
bin/config.sh: line 203: ${_arg_ig_mode^^}: bad substitution
```

this will only work for bash 4+

**Comment by jorgesanchezperez** [comment]
The syntax `^^` to convert a value to uppercase works only from bash 4.0 and above.
The issue raise when run the script using the `sh` explicitly.
The script convert the IG_mode selected by the user to uppercase because the json descriptor where is set that value require an uppercase value.
The solution is use the `tr` command:
`$(echo $_arg_ig_mode | tr '[:lower:]' '[:upper:]')` instead of `${_arg_ig_mode^^}
